server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_management_system_db
    username: library_management_system
    password: library_management_system123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: development
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  upload-directory: library_management_system
  folder-temp: ./library_management_system-temp/
  jwtSecret: "S3CR3TK3YAPPK3Y1234"

logging:
  level:
    com.sinaukoding.library_management_system: TRACE
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    defaultModelsExpandDepth: -1
    docExpansion: none
    tagsSorter: alpha
    operationsSorter: alpha